---
  - name: Setup custom nginx configuration file.
    template:
      src: nginx.conf.j2
      dest: "{{ nginx_conf_file_path }}"
      owner: root
      group: "{{ root_group }}"
      mode: 0644
    notify: reload nginx

  - name: Setup custom vhost configuration file.
    template:
      src: vhosts.j2
      dest: "{{ nginx_default_vhost_path }}"
      mode: 0644
    notify: reload nginx
